language: node_js
node_js: "8"
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
  - npm install
deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"
