INSERT INTO comments (user_name, comment, rating) VALUES ("Dave The Drinker", "This was a great place to drink", 5);
INSERT INTO comments (user_name, comment, rating) VALUES ("Sally the sober", "Not for me", 2);

INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Boddington's Brewery", "", "Manchester", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("JW Lees and Co", "Middleton Junction", "Manchester", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("BrewDog", "35 Peter St", "Manchester", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Track Brewing Company", "5 Sheffield Street", "Manchester", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Marbles Beer", "41 Williamson Street", "Manchester", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Cloud Water Brew Co.", "Piccadilly Trading Estate", "Manchester", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Alphabet Brewing Company", "99 N Western St", "Manchester", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Wander Beyond Brewing", "99 N Western St", "Manchester", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Beer Nouveau", "75N Western St", "Manchester", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Chorlton Brewing Company", "69 North Western Street", "Manchester", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Manchester Brewing Co", "66 North Western Street", "Manchester", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("SQUAWK Brewing Company", "Tounge Street", "Manchester", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Seven Bro7hers Brewery", "63 Way Bridge Enterprise Centre, Daniel Adamson Road, Salford Quays", "Manchester", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Thirst Class Ale", "Unit 16 Station Road Industrial Estate", "Stockport", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("First Chop", "B2 Barton Hall Business Park, Hardy Street", "Eccles", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Robinson's Brewery", "Unicorn Brewery, Stockport", "Cheshire", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("The Ticketybrew Company", "Unit 16 Waterloo Court", "Stalybridge", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Dunham Massey Brewing Company", "100 Oldfield Lanem Dunham Massey", "Bury", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Torrside", "The Warf Warehouse, New Mills, Marina New Mills", "Derbyshire", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Red Willow Brewery", "The Lounge Sutton Garrison", "Macclesfield", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Vocation Brewery", "Unit 8 Craggs Country Business Park New Road, Cragg Vale, Hebden Bridge", "West Yorkshire", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Prospect Brewery", "Unit 11 Bradley Hall Trading Estate, Standing", "Wigan", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Summer Wine Brewery", "Unit 15 Crossley Mills, New Mill Road, Hanley", "Holmfirth", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Thwaites Brewery", "Penny St", "Blackburn", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Crafty Dan", "Penny St", "Blackburn", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Moorhouse's Brewery", "4 Moorhouse Street", "Burnley", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Buxton", "Staden Business Park", "Buxton", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Wincle Beer Co", "Tolls Farm Barn, Barlow Hill, Wincle", "Macclesfield", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Sportsman Brewing Company", "1 St Johns Road", "Huddersfield", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Timothy Taylor", "Knowle Spring Brewery", "Keighley", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Ad Hop Brewing", "18 Servers St", "Liverpool", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Ossett Brewery", "Low Mill Rd", "Ossett", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Thorn Bridge Brewery", "Riverside Brewery", "Bakewell", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Mad Hatter Brewing Co", "15-37 Carol st. Palmer Hill Building", "Liverpool", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Black Lodge Brewing", "4 Kitchen Street, Baltic Triangle", "Liverpool", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Cains", "Stanhope Street", "Liverpool", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Saltaire Brewery", "Dockfield Rd", "Shipley", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Greens Brewery", "9 Briar Rhydding", "Baildon Shipley", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Abbey Dale Brewery", "Unit 8, Aizlewood Road", "Sheffield", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("The Porterhouse Brewing Co", "21-22 Maiden Lane", "London", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("The Draft House", "43 Goodge Street", "London", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Toast Ale", "105 Summer St", "London", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Orbit Beers", "225 & 228 Fielding St", "London", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("BrewDog", "113 Bayham Street, Camden Town", "London", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Frizzenti", "22-23 Widegate St, Spitalfields", "London", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Mondo Brewing Company", "86 Stewart's Road, Battersea", "London", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Hawkes Cidery", "96 Druid Street", "London", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Anspach & Hobday", "118 Druid Street, Bermondsey", "London", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("BrewDog", "51 Bethnel Green Road", "London", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Brew by Numbers", "79 Enid Street", "London", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Hammerton Brewery", "149 Roamn Way, Unit 9", "London", "N7 8XH");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("The Kernel Brewery", "Unit 11, Dockley Road Industrial Estate, Dockley Road", "London", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Hackney Brewery Ltd", "358 Laburnum St", "London", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("London Beer Lab", "41 Railway Arches Nursery Rd", "Brixton", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Sambrook's", "Unit 1 & 2 Yelverton Road, Battersea", "London", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Redchurch Brewery", "275-276 Poyser Street, Bethnal Green", "London", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("40FT Brewery", "Bootyard Abbott Street", "London", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Gower Brewery", "Oldwalls, Llanrhidian", "West Glamorgan", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Tomos Watkin", "Unit 3 Century Park, Valley Way", "Swansea", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Oast House Brewery", "Aberstywyth", "Ceredigion", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Otley Brewing Company", "Unit 42 Albion Industrual Estate", "Pontypridd", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("The Celt Experience", "Unit 2E Pontygwindy Rd", "Caerphilly", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Crafty Devil Brewing", "UNit 3 The Stoneyyard, Ninian Park Road", "Cardiff", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Brains Brewery", "The Cardiff Brewery, Crawshey Street", "Cardiff", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Firebrand Brewing Co", "5-7 Southgate Street, Lauceston", "Cornwall", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Tiny Rebel Brewing Co", "Maesglas Industrial Estate", "Newport", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Harbour Brewing Co", "Trekillick Farm", "Bodmin", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Yellow Belly Beer", "Whiterock Hill Pembrokestown", "Wexford", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Bristol Beer Factory", "The Old Brewery, Dunford Street", "Bristol", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Arbor Ales- The Three Tuns", "78 Saint George's Road, Hotwells", "Bristol", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Loch Lomond Brewery", "Unit 5, Lomon Industrial Estate Blcok 1", "West Dunbartonshire", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Williams Brothers Brewing Company", "New Alloa Brewery, Kelliebank", "Alloa", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("BrewDog", "143 Cowgate", "Edinburgh", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Beer52", "26 Howe Street", "Edinburgh", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Beergooder", "1-3 St Clome Street", "Edinburgh", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Pilot Beer", "22 St Jane St", "Edinburgh", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Caledonian Brewing", "42 Slateford Road", "Edinburgh", "");
INSERT INTO breweries (brewery_name, address, city, postal_code) VALUES ("Stewart Brewing", "Unit 5, 42 Dryden Road, Bilston Glen Ind Estate", "Loanhead", "");

